version: "2.4"
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: topsecret

  api:
    image: boas-vnext-identity/api:1.0
    volumes:
      - ./api:/app/api
      - ./tests:/app/tests
    ports:
      - 5000:5000
    environment:
      - AWS_ACCESS_KEY_ID=AKIA6PNTHUM5HFG3M6TJ
      - AWS_SECRET_ACCESS_KEY=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
    command: dotnet watch --project api run

  reverseproxy:
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - api

volumes:
  pg-data:
